#################################################################################
# Catena-X - Product Passport Consumer Frontend
#
# Copyright (c) 2022, 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
##################################################################################

---

# When deploying an EDC, there are various configuration parameters that should not be part of the configuration file.
# To not serve a bad example, this demo will set some settings using secrets as well. In a productive environment this secrets would probably be deployed independently.



{{- $psql_password := .Values.postgres.auth.password -}}
{{- $api_auth_key :=  .Values.controlplane.env.EDC_API_AUTH_KEY -}}
{{- $vault_token := .Values.controlplane.env.EDC_VAULT_HASHICORP_TOKEN -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: consumer-controlplane-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-consumer.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-tokenbased
  EDC_API_AUTH_KEY: {{ $api_auth_key | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/asset-index-sql
  EDC_DATASOURCE_ASSET_PASSWORD: {{ $psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-definition-store-sql
  EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: {{ $psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-negotiation-store-sql
  EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: {{ $psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/policy-store-sql
  EDC_DATASOURCE_POLICY_PASSWORD: {{ $psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/transfer-process-store-sql
  EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: {{ $psql_password | toString | quote }}
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $vault_token | toString | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: consumer-dataplane-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-consumer.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $vault_token | toString | quote }}


